apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-profile-service
  labels:
    app: user-profile-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-profile-service
  template:
    metadata:
      labels:
        app: user-profile-service
    spec:
      containers:
      - name: user-profile-service
        image: user-profile-service:latest
        ports:
        - containerPort: 8000
